# Generated by Django 5.2 on 2025-04-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(help_text='USER ID', max_length=300)),
                ('USER_NAME', models.CharField(max_length=300)),
                ('PHONE_NUMBER', models.IntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('MOVIE_NAME', models.CharField(max_length=300)),
                ('DATE', models.DateField()),
                ('SHOW_TIME', models.TimeField()),
                ('SEATS_Number', models.IntegerField()),
            ],
        ),
    ]
